### ISSUE TITLE
Exception in GetDynamicPagedList extension

### ISSUE THREAD

**Issue by Khan291** [sheryever/simple-access-orm#10]
```
            var result = _repoEntity.GetDynamicPagedList<JobwiseCandidateReportDTO>(startIndex, pageSize, sortExpression, whereParameters: new { competitionId });
            totalRows = result.TotalRows;
            return result.Data;
```

**Exception:**
`No mapping exists from object type System.Data.SqlClient.SqlParameter[] to a known managed provider native type.
`
**Stack**
```
   at System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters)
   at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at SimpleAccess.SqlServer.SqlSimpleAccess.ExecuteDynamics(String commandText, CommandType commandType, String fieldsToSkip, SqlParameter[] sqlParameters)
   at SimpleAccess.SqlServer.SqlSimpleAccess.ExecuteDynamics(String commandText, Object paramObject, String fieldsToSkip)
   at SimpleAccess.SqlServer.SqlEntityRepository.GetDynamicPagedList[TEntity](SqlParameter[] sqlParameters)
```

**Comment by sheryever** [comment]
Please update to new version
